<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-ModsenFinanceTracker.TelegramBot-94102eee-c883-4da7-853c-fa3ffc3c6813</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.11" />
    <PackageReference Include="Telegram.Bot" Version="22.10.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ModsenFinanceTracker.Application\ModsenFinanceTracker.Application.csproj" />
    <ProjectReference Include="..\ModsenFinanceTracker.Domain\ModsenFinanceTracker.Domain.csproj" />
    <ProjectReference Include="..\ModsenFinanceTracker.Infrastructure\ModsenFinanceTracker.Infrastructure.csproj" />
  </ItemGroup>
</Project>
